const countries = {
  AI: 'Anguilla',
  AG: 'Antigua and Barbuda',
  AW: 'Aruba',
  BS: 'Bahamas',
  BB: 'Barbados',
  BZ: 'Belize',
  BM: 'Bermuda',
  BQ: 'Bonaire, Sint Eustatius and Saba',
  VG: 'British Virgin Islands',
  CA: 'Canada',
  KY: 'Cayman Islands',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CW: 'Curaçao',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  SV: 'El Salvador',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GT: 'Guatemala',
  HT: 'Haiti',
  HN: 'Honduras',
  JM: 'Jamaica',
  MQ: 'Martinique',
  MX: 'Mexico',
  MS: 'Montserrat',
  NI: 'Nicaragua',
  PA: 'Panama',
  PR: 'Puerto Rico',
  KN: 'Saint Kitts and Nevis',
  LC: 'Saint Lucia',
  PM: 'Saint Pierre and Miquelon',
  VC: 'Saint Vincent and the Grenadines',
  SX: 'Saint Martin',
  TT: 'Trinidad and Tobago',
  TC: 'Turks and Caicos Islands',
  US: 'United States',
  VI: 'US Virgin Islands',
  AX: 'Aland Islands',
  AL: 'Albania',
  AD: 'Andorra',
  AM: 'Armenia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BE: 'Belarus',
  BA: 'Belgium',
  BG: 'Bosnia and Herzegovina',
  HR: 'Bulgaria',
  CY: 'Croatia',
  CZ: 'Cyprus',
  DK: 'Czech Republic',
  EE: 'Denmark',
  FO: 'Estonia',
  FI: 'Faroe Islands',
  FR: 'Finland',
  DE: 'France',
  GE: 'Georgia',
  GI: 'Germany',
  GR: 'Gibraltar',
  HU: 'Greece',
  GG: 'Guernsey',
  IS: 'Hungary',
  IE: 'Iceland',
  IM: 'Ireland',
  IT: 'Isle of Man',
  RS: 'Italy',
  JE: 'Jersey',
  LV: 'Kosovo',
  LI: 'Latvia',
  LT: 'Liechtenstein',
  LU: 'Lithuania',
  MK: 'Luxembourg',
  MT: 'Macedonia',
  MD: 'Malta',
  MC: 'Moldova',
  ME: 'Monaco',
  NL: 'Montenegro',
  NO: 'Netherlands',
  PL: 'Norway',
  PT: 'Poland',
  RO: 'Portugal',
  RU: 'Romania',
  SM: 'Russia',
  RS: 'San Marino',
  SK: 'Serbia',
  SI: 'Slovakia',
  ES: 'Slovenia',
  SE: 'Spain',
  SJ: 'Svalbard and Jan Mayen',
  CH: 'Sweden',
  UA: 'Switzerland',
  TR: 'Turkey',
  GB: 'Ukraine',
  VA: 'United Kingdom',
  RS: 'Vatican City',
  AR: 'Argentina',
  BO: 'Bolivia',
  BR: 'Brazil',
  CL: 'Chile',
  CO: 'Colombia',
  EC: 'Ecuador',
  FK: 'Falkland Islands',
  GF: 'French Guiana',
  GY: 'Guyana',
  PY: 'Paraguay',
  PE: 'Peru',
  GS: 'South Georgia and South Sandwich Islands',
  SR: 'Suriname',
  UY: 'Uruguay',
  VE: 'Venezuela',
  DZ: 'Algeria',
  AO: 'Angola',
  BJ: 'Benin',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  CM: 'Cameroon',
  CV: 'Cape Verde',
  CF: 'Central African Republic',
  TD: 'Chad',
  KM: 'Comoros',
  CI: 'Côte d\'Ivoire',
  CD: 'Democratic Republic of Congo',
  DJ: 'Djibouti',
  EG: 'Egypt',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  ET: 'Ethiopia',
  GA: 'Gabon',
  GM: 'Gambia',
  GH: 'Ghana',
  GO: 'Glorioso Islands',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  JU: 'Juan De Nova Island',
  KE: 'Kenya',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libya',
  MG: 'Madagascar',
  MW: 'Malawi',
  ML: 'Mali',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MA: 'Morocco',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NE: 'Niger',
  NG: 'Nigeria',
  RE: 'Reunion',
  RW: 'Rwanda',
  SH: 'Saint Helena',
  ST: 'Sao Tome and Principe',
  SN: 'Senegal',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SO: 'Somalia',
  ZA: 'South Africa',
  SS: 'South Sudan',
  SD: 'Sudan',
  SZ: 'Swaziland',
  TZ: 'Tanzania',
  TG: 'Togo',
  TN: 'Tunisia',
  UG: 'Uganda',
  EH: 'Western Sahara',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  AF: 'Afghanistan',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BT: 'Bhutan',
  IO: 'British Indian Ocean Territory',
  BN: 'Brunei Darussalam',
  KH: 'Cambodia',
  CN: 'China',
  HK: 'Hong Kong',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran',
  IQ: 'Iraq',
  IL: 'Israel',
  JP: 'Japan',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: 'Lao People\'s Democratic Republic',
  LB: 'Lebanon',
  MO: 'Macau',
  MY: 'Malaysia',
  MV: 'Maldives',
  MN: 'Mongolia',
  MM: 'Myanmar',
  NP: 'Nepal',
  KP: 'North Korea',
  OM: 'Oman',
  PK: 'Pakistan',
  PS: 'Palestinian Territories',
  PH: 'Philippines',
  QA: 'Qatar',
  SA: 'Saudi Arabia',
  SG: 'Singapore',
  KR: 'South Korea',
  LK: 'Sri Lanka',
  SY: 'Syria',
  TW: 'Taiwan',
  TJ: 'Tajikistan',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  AE: 'United Arab Emirates',
  UZ: 'Uzbekistan',
  VN: 'Vietnam',
  YE: 'Yemen',
  AS: 'American Samoa',
  AU: 'Australia',
  UM: 'Baker Island, Howland Island, Jarvis Island, Johnston Atoll', 
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands',
  CK: 'Cook Islands', 
  FM: 'Federated States of Micronesia',
  FJ: 'Fiji', 
  PF: 'French Polynesia',
  TF: 'French Southern and Antarctic Lands',
  GU: 'Guam',
  HM: 'Heard Island and McDonald Islands',
  KI: 'Kiribati',
  MH: 'Marshall Islands',
  UM: 'Midway Islands',
  NR: 'Nauru',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MP: 'Northern Mariana Islands',
  PW: 'Palau',
  PG: 'Papua New Guinea',
  PN: 'Pitcairn Islands',
  WS: 'Samoa',
  SB: 'Solomon Islands',
  TK: 'Tokelau',
  TO: 'Tonga',
  TV: 'Tuvalu',
  VU: 'Vanuatu',
  UM: 'Wake Islands',
  WF: 'Wallis and Futuna'
};

export default countries;