[
  "United States",
  "English-language films",
  "New York City",
  "Police",
  "President of the United States",
  "Donald Trump",
  "New York",
  "Democratic Party",
  "October 31",
  "Stock market",
  "New Jersey",
  "United Kingdom",
  "Stock",
  "Associated Press",
  "Manhattan",
  "Copyright",
  "All rights reserved",
  "2016",
  "World Trade Center",
  "Terrorism",
  "U.S. state",
  "Finance",
  "Ivana Trump",
  "Investment",
  "Bill Clinton",
  "Washington, D.C.",
  "Crime",
  "George W. Bush",
  "Fred Trump",
  "Constable",
  "London",
  "Los Angeles",
  "Lower Manhattan",
  "Law",
  "Economics",
  "United States Senate",
  "American football",
  "Federal Bureau of Investigation",
  "Management",
  "Marketing",
  "High school",
  "Jersey City, New Jersey",
  "Federal government of the United States",
  "Major League Baseball",
  "Chicago",
  "United States Congress",
  "Share",
  "American film actors",
  "Truck",
  "Twitter",
  "European Union",
  "Russia",
  "Barack Obama",
  "National Football League",
  "Medicine",
  "Automobile",
  "Hudson River",
  "Week-day names",
  "Attack",
  "California",
  "American films",
  "Port Authority Trans-Hudson",
  "Average",
  "Revenue",
  "President",
  "United States Constitution",
  "World War II",
  "United States House of Representatives",
  "Family",
  "Republican Party",
  "Government",
  "San Francisco Giants",
  "World Series",
  "State",
  "United Nations",
  "New York Yankees",
  "Education",
  "Wall Street",
  "The Quarter at Tropicana",
  "Bowl Championship Series",
  "Toronto",
  "Financial services",
  "Health care",
  "Petroleum",
  "Criminal law",
  "Empire State Building",
  "Canada",
  "National League",
  "According to Jim",
  "Japan",
  "India",
  "Los Angeles Dodgers",
  "September 11 attacks",
  "Security",
  "Islam",
  "Europe",
  "Halloween",
  "Attack!",
  "American television actors",
  "Democracy",
  "Hudson County, New Jersey",
  "Franklin D. Roosevelt",
  "Supreme Court of the United States",
  "Houston Astros",
  "Baseball",
  "National Basketball Association",
  "Google",
  "Cincinnati Reds",
  "American Civil War",
  "Manchester United F.C.",
  "Corporation",
  "Debut albums",
  "Tax",
  "Pickup truck",
  "Jury",
  "Association football",
  "Holland Tunnel",
  "Vice President of the United States",
  "Judge",
  "Money",
  "Real estate",
  "Australia",
  "Monday",
  "South Korea",
  "2017",
  "Sheriff",
  "Atlanta Braves",
  "Internet",
  "Prime minister",
  "Bank",
  "Film",
  "Business",
  "New York City Subway",
  "Port Authority of New York and New Jersey",
  "School",
  "Texas",
  "Premier League",
  "Human rights",
  "White House",
  "Jackie Robinson",
  "Germany",
  "Native Americans in the United States",
  "Richard Nixon",
  "Illinois",
  "E-mail",
  "Mayor of New York City",
  "New York Mets",
  "American Jews",
  "Death",
  "People's Republic of China",
  "Lawyer",
  "University",
  "Time",
  "Toronto Blue Jays",
  "Game",
  "Want",
  "France",
  "Humid subtropical climate",
  "North Carolina",
  "Mobile phone",
  "National Hockey League",
  "Police officer",
  "Board of directors",
  "United Arab Emirates",
  "Middle East",
  "Pacific Coast League",
  "Health",
  "Spain",
  "Court",
  "Immigration to the United States",
  "Boston Red Sox",
  "Thomas Jefferson",
  "Sexual intercourse",
  "City",
  "Israel",
  "Income",
  "Marriage",
  "Chief executive officer",
  "Law enforcement agency",
  "Shareholder",
  "New York metropolitan area",
  "Africa",
  "Massachusetts",
  "Nigeria",
  "England",
  "1981 World Series",
  "Property",
  "Bond",
  "Greenwich Village",
  "1963 World Series",
  "Transport",
  "United States dollar",
  "Voting",
  "Generally Accepted Accounting Principles",
  "Human sexual behavior",
  "Central bank",
  "Police brutality",
  "College football",
  "Pleading",
  "Cleveland Indians",
  "Rockefeller Center",
  "National League West",
  "Don Sutton",
  "Pacific Ocean",
  "Southern United States",
  "Utah",
  "New York City Police Department",
  "Allegation",
  "Woman",
  "Election",
  "United States presidential election, 2008",
  "Facebook",
  "College",
  "South Africa",
  "Road",
  "City of London",
  "Cancer",
  "International trade",
  "New Zealand",
  "Baltimore Orioles",
  "Dodger Stadium",
  "Saudi Arabia",
  "Asia",
  "Federal Reserve System",
  "Iraq War",
  "Social media",
  "North Korea",
  "Water",
  "UEFA Champions League",
  "Social network service",
  "Iraq",
  "Monetary policy",
  "Newark, New Jersey",
  "Nutrition",
  "American football positions",
  "WNYC",
  "Abuse",
  "Taxation in the United States",
  "1988 World Series",
  "Psychology",
  "Korean War",
  "Florida",
  "Employment",
  "George H. W. Bush",
  "Pennsylvania",
  "Korea",
  "Teacher",
  "Morgan Stanley",
  "Virginia",
  "Need",
  "Ronald Reagan",
  "Prison",
  "Texas Rangers",
  "Food",
  "Insurance",
  "Ohio",
  "Westminster system",
  "World",
  "Appeal",
  "Rape",
  "Criminal Investigation Department",
  "Delhi",
  "2005 World Series",
  "Arizona",
  "Super Bowl",
  "Chrysler Building",
  "Midtown Manhattan",
  "Elections",
  "Leo Durocher",
  "North America",
  "The Football League",
  "Natural gas",
  "China",
  "New Jersey Transit",
  "IPhone",
  "Hillary Rodham Clinton",
  "Debt",
  "National Collegiate Athletic Association",
  "Cabinet",
  "John McCain",
  "Pakistan",
  "Sales",
  "Legal terms",
  "Kevin Spacey",
  "Global city",
  "Sexual harassment",
  "Hospital",
  "Kentucky",
  "1965 World Series",
  "Management occupations",
  "Philadelphia Phillies",
  "Iran",
  "World Wide Web",
  "Interest rate",
  "Ice hockey",
  "New York City Council",
  "Halloween costume",
  "Sociology",
  "Gerald Ford",
  "Health insurance",
  "Arrest",
  "Stock exchange",
  "Cold War",
  "Murder",
  "Firearm",
  "Assault",
  "The Police",
  "Korean language",
  "Abraham Lincoln",
  "Los Angeles Memorial Coliseum",
  "Victim",
  "Music",
  "Italy",
  "P/E ratio",
  "Staten Island",
  "Taxation",
  "San Francisco 49ers",
  "Corporate governance",
  "Jordan",
  "Pharmacology",
  "Christianity",
  "Race",
  "Louisiana",
  "California League",
  "Republic of China",
  "All rights reversed",
  "Bus",
  "Future",
  "Basketball",
  "Turkey",
  "Olympic Games",
  "FA Cup",
  "Newspaper",
  "East Asia",
  "Philadelphia",
  "The Driver",
  "Real Madrid C.F.",
  "American Association",
  "Detroit Tigers",
  "Bullying",
  "Executive officer",
  "Queens",
  "Southeast Asia",
  "Advertising",
  "Better",
  "Trade",
  "American Broadcasting Company",
  "Maryland",
  "Minnesota",
  "Pennsylvania Station",
  "Vornado Realty Trust",
  "WANT",
  "Hawaii",
  "New York Stock Exchange",
  "Website",
  "Political philosophy",
  "Mass media",
  "Baseball statistics",
  "Washington Redskins",
  "Vehicle",
  "Price",
  "Report",
  "Republic",
  "Harvey Weinstein",
  "Play",
  "Senate",
  "Fiscal year",
  "La Liga",
  "Web browser",
  "Arabic language",
  "Law enforcement",
  "Login",
  "Sovereign state",
  "Latin America",
  "WNET",
  "Oak Ridge Associated Universities",
  "Dividend yield",
  "Violence",
  "Mother",
  "Income tax",
  "Following",
  "Retailing",
  "Weather",
  "Economic growth",
  "Michigan",
  "Apple Inc.",
  "Hong Kong",
  "Alaska",
  "Racism",
  "1978 World Series",
  "Dividend",
  "Manufacturing",
  "Theodore Roosevelt",
  "Vice president",
  "Customer service",
  "Washington",
  "Inflation",
  "Black-and-white films",
  "Currency",
  "Korean Peninsula",
  "Trick-or-treating",
  "Madison Square Garden",
  "Egypt",
  "Risk",
  "Republic of Ireland",
  "Chelsea F.C.",
  "Mexico",
  "Money supply",
  "Kim Il-sung",
  "Physician",
  "App Store",
  "Bank of England",
  "Colorado",
  "Georgia",
  "Tax refund",
  "Patient",
  "Philippines",
  "Pyongyang",
  "Walking",
  "Seoul",
  "Gun",
  "Syria",
  "Vermont",
  "Legislatures",
  "Plea",
  "Truck driver",
  "U.S. Securities and Exchange Commission",
  "Tampa Bay Rays",
  "Company",
  "FC Barcelona",
  "Carbon dioxide",
  "Year of birth missing",
  "United States Capitol",
  "President pro tempore of the United States Senate",
  "Supply and demand",
  "Coal",
  "1968",
  "Chuck Schumer",
  "Capitalism",
  "Salt Lake City",
  "Supreme court",
  "York",
  "Herbert Hoover",
  "Korean Demilitarized Zone",
  "Actor",
  "Hangul",
  "Health economics",
  "Vietnam War",
  "South Carolina",
  "Immune system",
  "NBC",
  "Hedge fund",
  "African American",
  "Houston",
  "Cleveland Browns",
  "Million",
  "Photography",
  "Construction",
  "E-mail address",
  "Love",
  "Trademark",
  "Hotel",
  "Microsoft",
  "Puerto Rico",
  "Bharatiya Janata Party",
  "Earth",
  "1967",
  "1973",
  "Madrid",
  "Spanish language",
  "Member of Parliament",
  "2016 Summer Olympics",
  "Question",
  "Energy",
  "School bus",
  "Corporate tax",
  "Nuclear weapon",
  "Big Ten Conference",
  "Fox Broadcasting Company",
  "Thomson Reuters",
  "Economy",
  "Arabian Peninsula",
  "Connecticut",
  "Student",
  "Vladimir Putin",
  "Web 2.0",
  "Baseball terminology",
  "American Football League",
  "User",
  "Computer",
  "Robert Mueller",
  "Clinical trial",
  "Progressive tax",
  "Credit card",
  "Immigration",
  "Drug addiction",
  "New York University",
  "Intercontinental Cup",
  "Thought",
  "14th Street",
  "Brazil",
  "Crimes",
  "Trial",
  "Income statement",
  "Rock music",
  "Tennessee",
  "Criminal justice",
  "1981",
  "Arsenal F.C.",
  "Segregated cycle facilities",
  "Capital punishment",
  "Indianapolis Colts",
  "Market",
  "Chairman",
  "Singapore",
  "Utility cycling",
  "Councillor",
  "German language",
  "1979",
  "Illness",
  "Internal combustion engine",
  "Domestic violence",
  "Gold",
  "2008–09 in English football",
  "Comment",
  "Kansas",
  "Wolverhampton Wanderers F.C.",
  "2015",
  "British Empire",
  "Coroner",
  "Minoru Yamasaki",
  "KILL",
  "Moving average",
  "Trump Organization",
  "Denver Broncos",
  "Ivanka Trump",
  "Oklahoma",
  "Don Drysdale",
  "The Bronx",
  "Dwight D. Eisenhower",
  "Euro",
  "Nevada",
  "County",
  "Semi-trailer truck",
  "Sun",
  "Asset",
  "Academy Award for Best Actor",
  "Input device",
  "Leeds United A.F.C.",
  "Source text",
  "2006 albums",
  "Chinese language",
  "Division of Korea",
  "Liverpool F.C.",
  "Drug",
  "Apartment",
  "Contract",
  "Broadsheet",
  "2003 invasion of Iraq",
  "Public health",
  "Primary school",
  "Traffic",
  "Amtrak",
  "Costume",
  "Leadership",
  "Christmas",
  "YouTube",
  "Legal professions",
  "Los Angeles Lakers",
  "MySpace",
  "Building",
  "Politics",
  "1963",
  "Atlantic Coast Conference",
  "Netherlands",
  "UEFA Cup Winners' Cup",
  "Gulf War",
  "The Final",
  "Chicago Cubs",
  "Prime Minister of the United Kingdom",
  "The Washington Post",
  "Newcastle United F.C.",
  "Hanja",
  "Missouri",
  "Syngman Rhee",
  "New York Knicks",
  "Gender",
  "Learning",
  "Ship",
  "Atlantic Ocean",
  "Chief executives",
  "Tommy Lasorda",
  "Wind",
  "New Orleans",
  "Qing Dynasty",
  "Tropical cyclone",
  "Cost",
  "Mutual fund",
  "Woolworth Building",
  "Brand",
  "Human",
  "Trump family",
  "Quarterback",
  "Value added tax",
  "The Apprentice",
  "Years in the future",
  "Football League Championship",
  "Customer",
  "Joe Biden",
  "Winter Olympic Games",
  "Great Salt Lake",
  "Project management",
  "Television",
  "Association of Public and Land-Grant Universities",
  "Collective investment scheme",
  "Oncology",
  "2014 Winter Olympics",
  "Smartphone",
  "Walk-off home run",
  "Central Asia",
  "New England Patriots",
  "Technology",
  "War",
  "The New York Times",
  "Discrimination",
  "Storm",
  "Driver's license",
  "Switzerland",
  "Left-wing politics",
  "Sea of Japan",
  "1970",
  "Military",
  "Scotland",
  "House",
  "Southeastern Conference",
  "Epidemiology",
  "United States Navy",
  "Cooking",
  "Gujarat",
  "Primary education",
  "Salt Lake County, Utah",
  "Peak oil",
  "2007",
  "University of Utah",
  "Americas",
  "New York's Village Halloween Parade",
  "Dubai",
  "New Mexico",
  "Uttar Pradesh",
  "Macroeconomics",
  "Theft",
  "Scientific method",
  "Soviet Union",
  "Jerusalem",
  "Kim Jong-il",
  "News agency",
  "Health care provider",
  "Caribbean",
  "Child abuse",
  "Names of large numbers",
  "Pregnancy",
  "Release",
  "Council of the European Union",
  "Indian National Congress",
  "Injury",
  "Prosecutor",
  "Refugee",
  "Dividend payout ratio",
  "Miami Dolphins",
  "Protest",
  "Constitutional monarchy",
  "Reuters",
  "Renting",
  "Sentence",
  "Al-Qaeda",
  "United States Coast Guard",
  "Art",
  "Buffalo Bills",
  "Elementary school",
  "Getty Images",
  "Obesity",
  "Staten Island Ferry",
  "Atlético Madrid",
  "Corporate finance",
  "Financial ratio",
  "Strategic management",
  "Western Asia",
  "1920",
  "Higher education",
  "Iowa",
  "Performance",
  "Agriculture",
  "Summer Olympic Games",
  "Unemployment",
  "United States Army",
  "Humid continental climate",
  "1918",
  "Blood",
  "Subscription business model",
  "Artificial intelligence",
  "Female",
  "Oakland Raiders",
  "Confederate States of America",
  "Head of state",
  "1941",
  "Arraignment",
  "Battery",
  "Bergen County, New Jersey",
  "Canadian football",
  "Boston Celtics",
  "Municipality",
  "Public transport",
  "Wisconsin",
  "Beijing",
  "Design",
  "Industry",
  "Precipitation",
  "1972",
  "Argentina",
  "Climate change",
  "New Delhi",
  "Research",
  "Dog",
  "Electoral College",
  "The A-Team",
  "Chemotherapy",
  "FA Community Shield",
  "Milk",
  "John Adams",
  "New York Jets",
  "Sexual assault",
  "Sustainability",
  "Belgium",
  "1946",
  "African Union",
  "Futures contract",
  "The Bill",
  "Federal government",
  "Science",
  "Andrew Cuomo",
  "Lagos",
  "Nazi Germany",
  "South America",
  "American Football Conference",
  "Downtown Hudson Tubes",
  "Global warming",
  "Law enforcement and society",
  "Political party",
  "World War I",
  "Dallas Cowboys",
  "1975",
  "English language",
  "Fox News Channel",
  "Income tax in the United States",
  "Legislature",
  "1986",
  "Coach",
  "Surgery",
  "Publishing",
  "Conservatism",
  "Malaysia",
  "Academic degree",
  "Common law",
  "Cricket",
  "Jews",
  "Judaism",
  "Economy of the People's Republic of China",
  "Pension",
  "1983",
  "Life",
  "Qatar",
  "Writing",
  "Rain",
  "Automotive industry",
  "Renewable energy",
  "1978",
  "Alcoholic beverage",
  "Cycling",
  "Dow Jones Industrial Average",
  "Major League Baseball All-Star Game",
  "Executive director",
  "Pharmaceutical drug",
  "Foreign exchange market",
  "Trucking industry in the United States",
  "Abbas Kiarostami",
  "New England",
  "BAFTA winners",
  "Idaho",
  "Lyndon B. Johnson",
  "Southern California",
  "Commonwealth of Nations",
  "Balance sheet",
  "Detective",
  "Indiana",
  "Ranking",
  "2008 Democratic National Convention",
  "City council",
  "Football",
  "Jack Lemmon",
  "Old Vic",
  "Serie A",
  "Trucks",
  "Yahoo!",
  "Black people",
  "Pittsburgh Steelers",
  "South Dakota",
  "Wasatch Front",
  "Afghanistan",
  "Food and Drug Administration",
  "Mumbai",
  "Northeastern United States",
  "Policy",
  "2007 singles",
  "Felony",
  "House of Lords",
  "IPod Touch",
  "Proposal",
  "United States Cabinet",
  "WWE Raw",
  "Graphic design",
  "1982",
  "Payment",
  "Electric charge",
  "Liberalism",
  "Narendra Modi",
  "Association of American Universities",
  "Computer security",
  "Indonesia",
  "2010s",
  "Developed country",
  "Brooklyn",
  "Mind",
  "NATO",
  "Transportation in New York City",
  "Airline",
  "Long Island",
  "Rome",
  "Cause of action",
  "Color",
  "John Kerry",
  "White people",
  "Infrastructure",
  "Sandy Koufax",
  "Kansas City Chiefs",
  "Fossil fuel",
  "San Francisco",
  "UEFA",
  "Childbirth",
  "Minister",
  "Restaurant",
  "Diplomacy",
  "2008 Summer Olympics",
  "Associated Press Television News",
  "Metastasis",
  "Ontario",
  "Arizona Diamondbacks",
  "Cloud computing",
  "Fruit",
  "High School Musical",
  "Mac OS X",
  "United States Department of Defense",
  "Ford Motor Company",
  "Light",
  "Miami",
  "Great Depression",
  "Nuclear power",
  "Elizabeth II of the United Kingdom",
  "Federal Reserve",
  "Indigenous peoples of the Americas",
  "Palestine",
  "Ireland",
  "New York Giants",
  "New York Post",
  "Palestinian people",
  "Presidential system",
  "West Bank",
  "Dividends",
  "Pioneer Theatre Company",
  "Childhood",
  "Manchester",
  "Overseas Chinese",
  "Fraud",
  "Parliament",
  "The Road",
  "Constitution",
  "United States Environmental Protection Agency",
  "Baseball rules",
  "Moscow",
  "Catholic Church",
  "Greece",
  "Innovation",
  "Midwestern United States",
  "Ottoman Empire",
  "Web page",
  "Christian terms",
  "Misdemeanor",
  "Financial ratios",
  "Grammy Award winners",
  "Murray, Utah",
  "The City",
  "Holding company",
  "1916",
  "Capital accumulation",
  "South Asia",
  "1945",
  "Hamas",
  "Harassment",
  "Orange County, California",
  "Coming out",
  "IPhone OS",
  "2003 Cricket World Cup",
  "Interest",
  "Sri Lanka",
  "Denmark",
  "Environmentalism",
  "French language",
  "Horror film",
  "Sibling",
  "Bank of America",
  "Green Bay Packers",
  "Heroin",
  "Mississippi River",
  "American stage actors",
  "Prime number",
  "Uzbekistan",
  "Middle school",
  "News",
  "Orel Hershiser",
  "Tourism",
  "United States Marine Corps",
  "1922",
  "Gold standard",
  "David Beckham",
  "News Corporation",
  "Oxygen",
  "Religion",
  "Pound sterling",
  "Seattle",
  "The Council",
  "Entrepreneurship",
  "Tottenham Hotspur F.C.",
  "Globalization",
  "Greenhouse gas",
  "Home run",
  "Days of the year",
  "Loan",
  "Parliamentary system",
  "1966",
  "2010 Winter Olympics",
  "Bill Belichick",
  "Sweden",
  "Roger Clemens",
  "Detroit",
  "Federal Reserve Act",
  "Meteorology",
  "Andrew Jackson",
  "British Columbia",
  "Christopher Nolan",
  "Cemetery",
  "Draft",
  "Funeral",
  "Standard Mandarin",
  "Chicago Bulls",
  "Healthcare",
  "Movie theater",
  "Culture",
  "United States Senate election in Illinois, 2004",
  "1977",
  "John F. Kennedy",
  "Pharmaceutical industry",
  "Second Intifada",
  "Athens",
  "Bishop",
  "Exchange-traded fund",
  "Taxation in the United Kingdom",
  "2006",
  "Burial",
  "Communication",
  "Local government",
  "Managing director",
  "Power",
  "Los Angeles Clippers",
  "Sudan",
  "Barcelona",
  "Broadcasting",
  "Olympic sports",
  "Tennis",
  "1980",
  "History of education",
  "Public finance",
  "Human migration",
  "Palestinian National Authority",
  "Speaker",
  "Trigraph",
  "United States Department of Homeland Security",
  "Designated hitter",
  "UTA TRAX",
  "Donald Trump, Jr.",
  "José Mourinho",
  "Law of the United States"
]