const data = require('./example_data_october2017.js');

const continents = {
  'US' : 'NA',
  'NZ' : 'AU',
  'AR' : 'SA',
  'NL' : 'EU',
  'FR' : 'EU',
  'CH' : 'EU',
  'CA' : 'NA',
  'BG' : 'EU',
  'PE' : 'SA',
  'ZW' : 'AF',
}

let mapData = {
  'NA' : {},
  'SA' : {},
  'EU' : {},
  'AF' : {},
  'APAC' : {},
  'AU' : {},
};

let results = data.results;

for(let i = 0; i < results.length; i++) {
  if(results[i].country) {
    let continent = continents[results[i].country];
    for(let j = 0; j < results[i].enriched_text.concepts.length; j++) {
      let currentConcept = results[i].enriched_text.concepts[j].text;
      if(mapData[continent][currentConcept]) {
        mapData[continent][currentConcept]++;
      } else {
        mapData[continent][currentConcept] = 1;
      }
    }
  }
}

// console.log('NA: ', mapData['NA']);
// console.log('SA: ', mapData['SA']);
// console.log('EU: ', mapData['EU']);
// console.log('AF: ', mapData['AF']);
// console.log('APAC: ', mapData['APAC']);
// console.log('AU: ', mapData['AU']);

for(key in mapData.NA) {
  if(mapData['NA'][key] > 2) {
    console.log(key + ': ' + mapData.NA[key]);
  }
}

/*

NA:  { 
  '2016': 1,
  'Portland, Maine': 1,
  'Portland Press Herald': 1,
  Wheel: 1,
  'French fries': 1,
  Sandwich: 1,
  'Falmouth, Maine': 1,
  Food: 1,
  'Yarmouth, Maine': 1,
  Potato: 1,
  Cheese: 1,
  'Reinventing the wheel': 1,
  Sandwiches: 1,
  'Melt sandwich': 1,
  Milk: 1,
  'The Link REIT': 2,
  Average: 3,
  'Stock market': 3,
  Stock: 3,
  Surgery: 1,
  'Financial services': 3,
  Investment: 1,
  Holding: 2,
  'Canadian dollar': 1,
  'American International Group': 1,
  Shareholder: 1,
  Share: 3,
  Hold: 1,
  Anesthesia: 1,
  'Ambulatory surgery center': 1,
  'Immigration to the United States': 2,
  'Donald Trump': 2,
  'Tucker Carlson': 1,
  Military: 1,
  'Military history': 1,
  War: 1,
  'United States': 5,
  'Foreign policy': 1,
  'Ivana Trump': 2,
  'Fred Trump': 2,
  Failure: 1,
  Success: 1,
  'Cannes Film Festival': 1,
  'Sexual intercourse': 2,
  'Human sexual behavior': 1,
  'Lorain County, Ohio': 1,
  'Viggo Mortensen': 1,
  'The Morning Journal': 1,
  Hay: 1,
  'The Whole Family': 1,
  Hayride: 1,
  'The Road': 1,
  'Lorain, Ohio': 1,
  'Morning Journal': 1,
  Halloween: 1,
  'New York City': 1,
  Fundraising: 1,
  'Non-profit organization': 1,
  'Hudson River': 1,
  Funding: 1,
  State: 2,
  'The arts': 1,
  Arts: 1,
  'According to Jim': 1,
  'Community Development Block Grant': 1,
  'New York': 1,
  Music: 1,
  'Somali people': 1,
  Somalia: 1,
  'Associated Press': 1,
  'Horn of Africa': 1,
  'Party leaders of the United States Senate': 1,
  'Green Bay Packers': 2,
  Mogadishu: 1,
  'Federal Reserve System': 1,
  'Somali language': 1,
  'Nuruddin Farah': 1,
  Ethiopia: 1,
  '1983 Beirut barracks bombing': 1,
  Sunday: 1,
  'Bowl Championship Series': 1,
  'History of Somalia': 1,
  'Philosophy of life': 1,
  'Blood sugar': 2,
  'Meaning of life': 1,
  Ontario: 1,
  Canada: 2,
  'New Democratic Party': 2,
  'House of Lords': 2,
  'Democratic Party': 2,
  Ottawa: 1,
  Business: 1,
  'United Kingdom': 1,
  'Bill Clinton': 1,
  'Speaker of the United States House of Representatives': 1,
  'House of Commons of Canada': 1,
  'Al Gore': 1,
  Manitoba: 1,
  'Small business': 1,
  'United States House of Representatives': 1,
  'The commons': 1,
  'The Canadian Press': 1,
  Retailing: 1,
  Liquidation: 1,
  Monday: 1,
  'The Speaker': 1,
  'Liberal Party of Canada': 2,
  'Government of Canada': 1,
  'Lower house': 1,
  'Sears Holdings Corporation': 1,
  'Parliament of the United Kingdom': 1,
  'Member of Parliament': 1,
  Surnames: 1,
  'Schweizer gliders': 1,
  'Pittsburgh metropolitan area': 1,
  'National Soaring Museum': 1,
  California: 2,
  'U.S. state': 1,
  Dog: 1,
  'Sacramento, California': 1,
  'Oakland, California': 1,
  'Los Angeles': 1,
  'Pacific Ocean': 1,
  'Mediterranean climate': 1,
  'California Gold Rush': 1,
  'San Francisco': 1,
  'National Basketball Association': 1,
  'Dianne Feinstein': 1,
  Pets: 1,
  Nevada: 1,
  'Rock and roll': 1,
  'Native Americans in the United States': 1,
  'Major League Baseball': 1,
  'Alta California': 1,
  'Governor of California': 1,
  'San Francisco International Airport': 1,
  'Global city': 1,
  'Pacific Time Zone': 1,
  'San Andreas Fault': 1,
  'West Coast of the United States': 1,
  Oregon: 1,
  '1984 Summer Olympics': 1,
  'Sovereign state': 1,
  'California State Route 1': 1,
  'California State University': 1,
  'Greater Los Angeles Area': 1,
  Delaware: 1,
  'States of the United States': 1,
  'San Francisco Bay Area': 1,
  'Benicia, California': 1,
  'San Francisco Bay': 1,
  'San Francisco 49ers': 3,
  'Vallejo, California': 1,
  'Los Angeles Lakers': 1,
  'University of Southern California': 1,
  'Oakland Raiders': 2,
  'Los Angeles metropolitan area': 1,
  'San Jose, California': 1,
  'California State Senate': 1,
  'Consumer protection': 1,
  'Oakland Athletics': 1,
  'San Francisco Giants': 1,
  Corporation: 2,
  'Materials science': 1,
  Revenue: 1,
  Company: 2,
  'Limited liability company': 1,
  'The Quarter at Tropicana': 1,
  'Types of business entity': 1,
  Solomon: 1,
  Pinophyta: 1,
  Tanakh: 1,
  'Books of Kings': 1,
  'Presbyterian polity': 1,
  Calvinism: 1,
  'Book of Proverbs': 1,
  Septuagint: 1,
  'Books of the Hebrew Bible': 1,
  'Bob Ezrin': 1,
  'Protestant Reformation': 1,
  Psalms: 1,
  'Christian terms': 1,
  'Christian denomination': 1,
  'Queen of Sheba': 1,
  Adonijah: 1,
  'Washington Redskins': 1,
  'American football': 3,
  'National Football League': 3,
  'Mike Shanahan': 1,
  Maryland: 1,
  'Dallas Cowboys': 1,
  'San Diego Chargers': 1,
  'American football positions': 1,
  'Houston Texans': 1,
  'Denver Broncos': 1,
  '2009 NFL season': 1,
  'Super Bowl': 1,
  'Monday Night Football': 1,
  FedExField: 1,
  'Tampa Bay Buccaneers': 1,
  'New York Giants': 1,
  'Brian Hoyer': 1,
  'Miami Dolphins': 1,
  'Canadian football': 1,
  'Pro Bowl': 1,
  'St. Louis Rams': 1,
  'The Star-Spangled Banner': 1,
  'New Orleans Saints': 1,
  'American football quarterbacks': 1,
  'Kansas City Chiefs': 1,
  'National Football Conference': 1,
  'Detroit Lions': 1,
  'Prince George\'s County, Maryland': 1,
  'Philadelphia Eagles': 1,
  'Seattle Seahawks': 1,
  'End zone': 1,
  'Atlanta Falcons': 1,
  'Deion Sanders': 1,
  'New York Jets': 1,
  'Jacksonville Jaguars': 1,
  Touchdown: 1,
  'Kyle Shanahan': 1,
  'Kirk Cousins': 1,
  'Landover, Maryland': 1,
  'NFC East': 1,
  Cornerback: 2,
  'Offensive coordinator': 1,
  'Bruce Smith': 1,
  'Norv Turner': 1,
  'Joe Gibbs': 1,
  'Indianapolis Colts': 1,
  'Season ticket': 1,
  'National Hockey League': 1,
  Player: 1,
  'Legion of Super-Heroes': 1,
  'The Players': 1,
  'Pembroke, Ontario': 1,
  'The A-Team': 1,
  'Dale McTavish': 1,
  Digestion: 1,
  'Surya Namaskara': 1,
  Nutrition: 1,
  'Human gastrointestinal tract': 1,
  Twist: 1,
  Elbow: 1,
  'Human anatomy': 1,
  'Randomized controlled trial': 1,
  Epidemiology: 1,
  Medicine: 1,
  Stomach: 1,
  'Yoga positions': 1,
  'Diabetes mellitus': 1,
  'Digestive system': 1,
  Mantra: 1,
  'Evidence-based medicine': 1,
  'Health insurance': 1,
  'Left-handedness': 2,
  Organ: 1,
  Exhalation: 1,
  Metabolism: 1,
  'Middle East': 1,
  'North Africa': 1,
  Egypt: 1,
  Jordan: 1,
  Islam: 1,
  'Arabian Peninsula': 1,
  Libya: 1,
  Asia: 1,
  'Near East': 1,
  'Ottoman Empire': 1,
  Kuwait: 1,
  Maghreb: 1,
  'Saudi Arabia': 1,
  'Far East': 1,
  'Western Asia': 1,
  Cairo: 1,
  Baghdad: 1,
  'Arabic language': 1,
  Caliphate: 1,
  Orientalism: 1,
  'Indian Ocean': 1,
  'Pussycat Dolls': 1,
  PCD: 1,
  'Kaya Jones': 1,
  'ARIA Charts': 1,
  '2000s music groups': 1,
  'Jessica Sutta': 1,
  'Pussycat Dolls Present: The Search For the Next Doll': 1,
  'British Columbia': 1,
  Elections: 1,
  Election: 1,
  'British Columbia general election, 2005': 1,
  'Liberalism worldwide': 1,
  'Stephen Harper': 1,
  Voting: 1,
  'Paul Martin': 1,
  Liberal: 1,
  Liberalism: 1,
  'Westminster system': 1,
  'Ontario Liberal Party': 1,
  'Jean Chrétien': 1,
  'Year of birth missing': 1,
  'Liberal Democrats': 1,
  'Coalition government': 1,
  Democracy: 1,
  'Cognizant Technology Solutions': 1,
  Chennai: 1,
  'World War II': 1,
  Russia: 1,
  Sweden: 1,
  Laptop: 1,
  Linux: 1,
  Metaphysics: 1,
  Finland: 1,
  England: 1,
  'Baltic Sea': 1,
  'Athletic nickname': 1,
  'Personal computer': 1,
  'President of the United States': 1,
  Diplomacy: 1,
  'White House': 1,
  'Business school': 1,
  'The Apprentice': 1,
  'International relations': 1,
  'Beth Phoenix': 1,
  '"I Quit" match': 1,
  'Tommy Dreamer': 1,
  'Collective bargaining': 1,
  Negotiation: 1,
  Grievance: 1,
  'English-language films': 2,
  'Joe Biden': 1,
  'Hillary Rodham Clinton': 1,
  'Hong Kong': 1,
  Short: 1,
  'Economy of the People\'s Republic of China': 1,
  '2016 Summer Olympics': 1,
  'Vice President of the United States': 1,
  'White supremacy': 1,
  Supremacism: 1,
  'Ku Klux Klan': 1,
  Racism: 1,
  'Heroes of the Fiery Cross': 1,
  Discrimination: 1,
  'Racial segregation': 1,
  Race: 1,
  'The Good Citizen': 1,
  'Sexual orientation': 1,
  'Anti-miscegenation laws': 1,
  'Nordic race': 1,
  'Free group': 1,
  'Algebraic topology': 1,
  Learning: 1,
  Crime: 2,
  'Grant County, Washington': 1,
  Police: 1,
  Constable: 1,
  'Hamilton, Ontario': 2,
  'The Cop': 1,
  'Criminal law': 1,
  Thunderstorm: 1,
  Wind: 1,
  Precipitation: 1,
  Tree: 1,
  Weather: 1,
  Tornado: 1,
  Branch: 1,
  'Weather forecasting': 1,
  'Power outage': 1,
  'The Strongest': 1,
  'Wind shear': 1,
  Afternoon: 1,
  WIND: 1,
  Evening: 1,
  'Tropical cyclone': 1,
  'Northwest Smith': 1,
  Pool: 1,
  'Dale Earnhardt': 1,
  'Daytona 500': 1,
  'NASCAR drivers': 1,
  'Talladega Superspeedway': 1,
  'Nationwide Series': 1,
  '2008 NASCAR Sprint Cup Series': 1,
  'Jeff Gordon': 1,
  'Sprint Cup Series': 1,
  'American racecar drivers': 1,
  'Bill Elliott': 1,
  'Dale Earnhardt, Jr.': 1,
  '2001 NASCAR Winston Cup Series': 1,
  'Tony Stewart': 1,
  'NASCAR Rookie of the Year': 1,
  '2009 NASCAR Sprint Cup Series': 1,
  'Jamie McMurray': 1,
  'AMP Energy 500': 1,
  'Jimmie Johnson': 1,
  'Camping World Truck Series': 1,
  'Hendrick Motorsports': 1,
  'Richmond International Raceway': 1,
  'Charlotte Motor Speedway': 1,
  'NASCAR owners': 1,
  'Daytona 500 winners': 1,
  'Matt Kenseth': 1,
  'Kevin Harvick': 1,
  'Daytona International Speedway': 1,
  'Budweiser Shootout': 1,
  'Richard Petty': 1,
  'Darrell Waltrip': 1,
  'Michael Waltrip': 1,
  'International Race of Champions drivers': 1,
  'Death of Dale Earnhardt': 1,
  '2006 NASCAR Nextel Cup Series': 1,
  '2007 NASCAR Nextel Cup Series': 1,
  'Richard Childress Racing': 1,
  'Gatorade Duel': 1,
  '2009 Daytona 500': 1,
  'Darlington Raceway': 1,
  'NASCAR Sprint All-Star Race': 1,
  'Richard Childress': 1,
  'Jeffrey Earnhardt': 1,
  'Bobby Labonte': 1,
  'Kerry Earnhardt': 1,
  'Dale Earnhardt, Inc.': 1,
  'Kurt Busch': 1,
  'International Race of Champions': 1,
  '2006 NASCAR Busch Series': 1,
  'Food City 500': 1,
  Robbery: 1,
  Theft: 1,
  Begging: 1,
  'The Register': 1,
  Face: 1,
  Carjacking: 1 }

SA:  { 'Master\'s degree': 1,
  'Bachelor\'s degree': 1,
  'Academic degree': 1,
  'Human resource management': 1,
  Doctorate: 1,
  Licentiate: 1,
  'Bachelor of Science': 1,
  Diplom: 1,
  Following: 1,
  Freelancer: 1,
  Report: 1,
  'Engineer\'s degree': 1,
  'Human resources': 1,
  'Christopher Nolan': 1,
  Typography: 1,
  Logo: 1,
  'Graphic design': 1,
  Microsoft: 1,
  Trigraph: 1,
  'Communication design': 1,
  Gh: 1,
  'NCR Corporation': 1,
  Retailing: 1,
  Hairstyle: 1 
}

EU:  { 
  '1920': 1,
  '1924': 1,
  '1932': 1,
  '1942': 1,
  '1944': 1,
  '1946': 1,
  '1948': 1,
  '1953': 1,
  '1954': 1,
  '1962': 1,
  '1964': 1,
  '1965': 1,
  '1966': 1,
  '1967': 1,
  '1968': 1,
  '1969': 1,
  '1970': 1,
  '1971': 1,
  '1972': 1,
  '1973': 1,
  '1974': 1,
  '1976': 1,
  '1977': 1,
  '1979': 1,
  '1981': 1,
  '1982': 1,
  '1986': 1,
  '1987': 1,
  '1988': 1,
  '2000': 1,
  '2006': 1,
  '2007': 1,
  '2008': 1,
  'Funny animal': 1,
  Trigraph: 1,
  Gh: 1,
  Game: 1,
  'Jennifer Lopez': 1,
  'Black Death': 1,
  Epidemiology: 1,
  'Yersinia pestis': 1,
  'Pneumonic plague': 1,
  'Bubonic plague': 1,
  Plague: 1,
  Risk: 1,
  October: 1,
  'Bacterial diseases': 1,
  'Days of the year': 1,
  'Infectious disease': 1,
  'Pasteur Institute': 1,
  'Incubation period': 1,
  'Precautionary principle': 1,
  'Indian Ocean': 1,
  'Mahé, Seychelles': 1,
  Mauritius: 1,
  Kathmandu: 1,
  Nepal: 1,
  'Nepali language': 1,
  Hiking: 1,
  'Piazza del Popolo': 1,
  'Kathmandu Valley': 1,
  'Patan, Lalitpur': 1,
  Earthquake: 1,
  'Kathmandu District': 1 
}

AF:  { 
  'Stock market': 1,
  'Robert Mugabe': 1,
  Zimbabwe: 1,
  'Market capitalization': 1,
  Stock: 1,
  'Morgan Tsvangirai': 1,
  Gain: 1,
  Harare: 1,
  'Names of large numbers': 1,
  Durban: 1,
  'Moses Mabhida Stadium': 1,
  '2010 FIFA World Cup': 1,
  'Single-elimination tournament': 1,
  'South African football': 1,
  'Kings Park Stadium': 1,
  'Kings Park Sporting Precinct': 1,
  'Cape Town': 1,
  Game: 1,
  Final: 1,
  Soweto: 1 
}

APAC:  {}

AU:  { 
  'Board of directors': 1,
  'New Zealand': 1,
  'New Zealand wine': 1,
  Management: 1,
  Chairman: 1,
  Wine: 1,
  'Australian and New Zealand Wine Industry Journal': 1,
  'Corporate governance': 1,
  Manager: 1,
  'Wairau River': 1,
  'South Island': 1,
  England: 1,
  Chardonnay: 1 
}

*/